apiVersion: v1
kind: Service
metadata:
  name: longevity-coach-service
spec:
  selector:
    app: longevity-coach
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
