apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longevity-app
spec:
  rules:
    - host: longevity.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: longevity-app
                port:
                  number: 80
